blank_issues_enabled: false
contact_links:
  - name: "Project README / docs"
    url: "https://github.com/DenisUstinov/mail-alias-platform/blob/main/README.md"
    about: "Read README/docs before creating an issue."
