name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run tests
        run: |
          if [ -d services/mail-alias-api/tests ]; then
            poetry run pytest -q services/mail-alias-api/tests
          else
            echo "No tests directory — skipping pytest"
          fi

      - name: Lint (optional)
        run: |
          if command -v ruff >/dev/null 2>&1; then
            poetry run ruff check .
          else
            echo "ruff not installed — skipping lint"
          fi
